	
static JSValueRef jst_string_read JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_field JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_line JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_format JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_indexOf JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF8 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF8 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF16 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF16 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF32 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF32 JSTDeclareFunction (pointer, index, length) {
	return JSTValueNull;
}


