	
static JSValueRef jst_string_read JSTDeclareFunction (pointer, length) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_field JSTDeclareFunction (pointer, delimiter) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_line JSTDeclareFunction (pointer, index) {
	return JSTValueNull;
}

static JSValueRef jst_string_read_format JSTDeclareFunction (pointer, format, ...) {
	return JSTValueNull;
}

static JSValueRef jst_string_indexOf JSTDeclareFunction (pointer, substring) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF8 JSTDeclareFunction (string) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF8 JSTDeclareFunction (pointer, boolOptionFree) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF16 JSTDeclareFunction (string) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF16 JSTDeclareFunction (pointer, boolOptionFree) {
	return JSTValueNull;
}

static JSValueRef jst_string_toUTF32 JSTDeclareFunction (string) {
	return JSTValueNull;
}

static JSValueRef jst_string_fromUTF32 JSTDeclareFunction (pointer, boolOptionFree) {
	return JSTValueNull;
}


