
BUILD_OBJECT_WILDCARD := $(BUILD_OUTPUT)/%.$(BUILD_OBJECT_EXTENSION)
BUILD_CPU_CONFIG_OBJECT := $(BUILD_OUTPUT)/jscpucfg.$(BUILD_OBJECT_EXTENSION)
BUILD_CPU_CONFIG := $(BUILD_OUTPUT)/jscpucfg$(BUILD_EXECUTABLE_SUFFIX)
BUILD_SCANNER_OBJECT := $(BUILD_OUTPUT)/jsscan.$(BUILD_OBJECT_EXTENSION)
BUILD_KEYWORD_GENERATOR := $(BUILD_OUTPUT)/jskwgen$(BUILD_EXECUTABLE_SUFFIX)
BUILD_KEYWORD_GENERATOR_OBJECT := $(BUILD_OUTPUT)/jskwgen.$(BUILD_OBJECT_EXTENSION)
BUILD_INVOKE_OBJECT := $(BUILD_OUTPUT)/jsinvoke.$(BUILD_OBJECT_EXTENSION)

BUILD_LIBRARY_OBJECTS := \
$(BUILD_OUTPUT)/dyncall/*.$(BUILD_OBJECT_EXTENSION) \
$(BUILD_OUTPUT)/jsapi.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsarena.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsarray.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsatom.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsbool.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jscntxt.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsdate.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsdbgapi.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsdhash.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsdtoa.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsemit.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsexn.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsfun.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsgc.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jshash.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsinterp.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsinvoke.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsiter.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jslock.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jslog2.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jslong.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsmath.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsnum.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsobj.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsopcode.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsparse.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsprf.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsregexp.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsscan.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsscope.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsscript.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsstr.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/jsutil.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsxdrapi.$(BUILD_OBJECT_EXTENSION)	\
$(BUILD_OUTPUT)/jsxml.$(BUILD_OBJECT_EXTENSION)		\
$(BUILD_OUTPUT)/prmjtime.$(BUILD_OBJECT_EXTENSION)

BUILD_STATIC_LIBRARY := $(BUILD_DIST)/$(BUILD_ARCHIVE_PREFIX)jse.$(BUILD_ARCHIVE_EXTENSION)
BUILD_SHARED_LIBRARY := $(BUILD_DIST)/$(BUILD_LIBRARY_PREFIX)jse.$(BUILD_LIBRARY_EXTENSION)

BUILD_SHELL := $(BUILD_DIST)/js$(BUILD_EXECUTABLE_SUFFIX)

