#ifndef JST

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>

#include <unistd.h>

#include <errno.h>

#include <string.h>
#include <wchar.h>
#include <uchar.h>

#include <iconv.h>

#include "JavaScriptCore.inc"
#include "glib.inc"
#include "dyncall.inc"

#include "JSTools/Base.inc"
#include "JSTools/Class.inc"
#include "JSTools/Constructor.inc"
#include "JSTools/Context.inc"
#include "JSTools/Declare.inc"
#include "JSTools/Function.inc"
#include "JSTools/Native.inc"
#include "JSTools/Object.inc"
#include "JSTools/Script.inc"
#include "JSTools/Stack.inc"
#include "JSTools/String.inc"
#include "JSTools/Value.inc"

#endif

